const CONTENT = {

  heroImages: [
    // "images/hero/photo-1.jpg",
    // "images/hero/photo-2.jpg",
    // "images/hero/photo-3.jpg",
    // "images/hero/photo-4.jpg",
    // "images/hero/photo-5.jpg",
  ],

  name: "Raghav Kohli",
  title: "Urban Designer · Climate Strategist",
  location: "Bengaluru, India",
  email: "raghav.kohli.work@gmail.com",
  linkedin: "linkedin.com/in/raghavkohli31",

  hero: {
    headline: ["Cities", "Community", "Climate"],
    statement: "I went to the ground first — five months in Mumbai's fishing villages before I drew a single line.",
  },

  projects: [

    {
      id: "iclei",
      title: "ICLEI",
      subtitle: "Local Governments for Sustainability",
      role: "Project Officer, Climate & Energy",
      year: "2024",
      category: "climate",
      featured: true,
      description: "Led climate strategy and policy work across South and Southeast Asia.",
      subprojects: [
        {
          id: "malaysia",
          title: "Malaysia Green City Action Plan",
          description: "City-level climate strategy spanning 5 municipalities, coordinated with national government counterparts.",
          images: [],
          video: "",
        },
        {
          id: "capacities",
          title: "CapaCities",
          description: "Capacity building programme for local government officials across South Asian cities, focused on developing Climate Resilient City Action Plans (CRCAPs) in partnership with municipal corporations.",
          images: [
            "images/ICLEI/CapaCities Overview/CRCAP Overview-final-03.jpg",
            "images/ICLEI/CapaCities Overview/CRCAP Overview-final-04-04.jpg",
            "images/ICLEI/CapaCities Overview/CRCAP Overview-final-05.jpg",
            "images/ICLEI/CapaCities Overview/CRCAP Overview-final-06.jpg",
          ],
          video: "",
        },
        {
          id: "loss-damage",
          title: "Loss & Damage",
          description: "Multilateral policy briefs on Loss & Damage for international climate negotiations.",
          images: [],
          video: "",
        },
        {
          id: "urban95",
          title: "Udaipur Urban95",
          description: "Child-Friendly Cities assessment integrating child-sensitive spatial design into the municipal planning framework.",
          images: [],
          video: "",
        },
        {
          id: "clean-energy",
          title: "US–South Asia Mayoral Platform",
          description: "Clean Energy platform facilitating dialogue between city leaders across two continents.",
          images: [],
          video: "",
        },
        {
          id: "vadodara-crcap",
          title: "Vadodara Climate Resilient City Action Plan",
          description: "Towards a Net Zero Future — a comprehensive climate action plan for Vadodara Municipal Corporation, developed with ICLEI South Asia. Covers climate risk assessment, sectoral emissions, and adaptation and mitigation action plans across transport, energy, water, waste, and urban greening. August 2024.",
          viewer: "reader",
          images: [],
          video: "",
        },
        {
          id: "ahmedabad-crcap",
          title: "Ahmedabad Climate Resilient City Action Plan",
          description: "Towards a Net Zero Future — a comprehensive climate action plan for Ahmedabad Municipal Corporation, developed with ICLEI South Asia. Covers climate risk assessment, sectoral emissions, and adaptation and mitigation action plans across transport, energy, water, waste, and urban greening. July 2023.",
          viewer: "reader",
          images: [],
          video: "",
        },
        {
          id: "surat-crcap",
          title: "Surat Climate Resilient City Action Plan",
          description: "Net-Zero Climate Resilient City Action Plan for Surat Municipal Corporation, developed with ICLEI South Asia and C40 Cities. Covers sectoral emissions, climate risk, and comprehensive adaptation and mitigation action plans. June 2025.",
          viewer: "reader",
          images: [],
          video: "",
        },
      ],
    },

    {
      id: "niua",
      title: "NIUA",
      subtitle: "National Institute of Urban Affairs, MoHUA India",
      role: "Climate Fellow, Climate Center for Cities",
      year: "2023",
      category: "climate",
      featured: true,
      description: "Climate policy research and toolkit development for Indian cities.",
      subprojects: [
        {
          id: "state-of-cities",
          title: "State of Cities",
          description: "Towards Low Carbon and Resilient Pathways — national policy report covering 15 Indian cities, published by MoHUA. Presented at the G20 Urban20 Summit, Ahmedabad, July 2023.",
          viewer: "reader",
          stats: [
            { n: "15",   l: "Cities Profiled" },
            { n: "24M",  l: "People" },
            { n: "38M",  l: "tCO₂e GHG" },
            { n: "319",  l: "Actions Mapped" },
          ],
          sections: [
            { label: "Cover",         start: 1,  end: 3  },
            { label: "Foreword",      start: 4,  end: 7  },
            { label: "Global View",   start: 8,  end: 12 },
            { label: "National View", start: 13, end: 15 },
            { label: "City View",     start: 16, end: 32 },
            { label: "Way Forward",   start: 33, end: 38 },
          ],
          cities: [
            { name: "Ahmedabad",        state: "Gujarat",          page: 18 },
            { name: "Coimbatore",       state: "Tamil Nadu",        page: 19 },
            { name: "Gwalior",          state: "Madhya Pradesh",    page: 20 },
            { name: "Kochi",            state: "Kerala",            page: 21 },
            { name: "Nagpur",           state: "Maharashtra",       page: 22 },
            { name: "Panaji",           state: "Goa",               page: 23 },
            { name: "Pimpri-Chinchwad", state: "Maharashtra",       page: 24 },
            { name: "Rajkot",           state: "Gujarat",           page: 25 },
            { name: "Shimla",           state: "Himachal Pradesh",  page: 26 },
            { name: "Siliguri",         state: "West Bengal",       page: 27 },
            { name: "Thane",            state: "Maharashtra",       page: 28 },
            { name: "Tiruchirappalli",  state: "Tamil Nadu",        page: 29 },
            { name: "Tirunelveli",      state: "Tamil Nadu",        page: 30 },
            { name: "Udaipur",          state: "Rajasthan",         page: 31 },
            { name: "Vadodara",         state: "Gujarat",           page: 32 },
          ],
          images: [
            "images/NIUA/State-of-cities/Final Book version_page-0001.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0002.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0003.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0004.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0005.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0006.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0007.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0008.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0009.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0010.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0011.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0012.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0013.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0014.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0015.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0016.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0017.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0018.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0019.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0020.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0021.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0022.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0023.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0024.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0025.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0026.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0027.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0028.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0029.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0030.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0031.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0032.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0033.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0034.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0035.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0036.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0037.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0038.jpg",
          ],
          video: "",
        },
        {
          id: "compendium",
          title: "Good Practices Compendium",
          description: "Researched and documented climate interventions across 15+ municipalities for national policy adoption.",
          images: [],
          video: "",
        },
        {
          id: "nbs-toolkit",
          title: "Nature-based Solutions Toolkit",
          description: "Practical NbS implementation guidance developed for urban local bodies across India.",
          images: [],
          video: "",
        },
      ],
    },

    {
      id: "perspectives",
      title: "Perspectives",
      subtitle: "Community Platform",
      role: "Co-founder",
      year: "2025 – Present",
      category: "community",
      featured: true,
      description: "8 to 1,000+ members through word of mouth. A community built around structured human conversation.",
      stats: [
        { number: "200+", label: "Conversations hosted" },
        { number: "1K+",  label: "Members, zero paid acquisition" },
        { number: "3",    label: "Formats — Spheres, Circles, Home" },
      ],
      conversations: [
        {
          id: "conv-001",
          title: "What does it mean to belong to a city?",
          description: "A conversation about urban identity, belonging, and what makes a city feel like home.",
          initiator: "Raghav Kohli",
          date: "2025-03",
          format: "Sphere",
          photo: "",
          recording: "",
        },
        {
          id: "conv-002",
          title: "On grief and growth",
          description: "An intimate Sphere exploring how loss shapes identity and the relationships we build after.",
          initiator: "Shreshtha",
          date: "2025-04",
          format: "Sphere",
          photo: "",
          recording: "",
        },
        {
          id: "conv-003",
          title: "Climate anxiety and what we do with it",
          description: "How do people working in climate actually feel about the future? An honest conversation.",
          initiator: "Raghav Kohli",
          date: "2025-05",
          format: "Circle",
          photo: "",
          recording: "",
        },
        {
          id: "conv-004",
          title: "Career pivots and the identity that follows",
          description: "When you change what you do, who do you become? Hosted across three living rooms.",
          initiator: "Avani",
          date: "2025-06",
          format: "Home",
          photo: "",
          recording: "",
        },
      ],
      subprojects: [],
    },

    {
      id: "cept",
      title: "CEPT University",
      subtitle: "Centre for Environmental Planning & Technology",
      role: "Bachelors in Urban Design",
      year: "2017 – 22",
      category: "design",
      featured: true,
      description: "Five years of urban design education, research, and fieldwork.",
      subprojects: [
        {
          id: "living-heritage",
          title: "Living Heritage",
          description: "Co-designing to Revive Historical Identity — a participatory urban design project at Ambli village, Ahmedabad. Focused on reviving the historical identity of a peri-urban heritage settlement through community co-design. Winner, CEPT Student Excellence Award. Semester 5, 2019.",
          images: [
            "images/CEPT/Living Heritage/Raghav Kohli_Strategy Map_Ambli_Ahmedabad.jpg",
            "images/CEPT/Living Heritage/raghav_panel.jpg",
            "images/CEPT/Living Heritage/axo.jpg",
            "images/CEPT/Living Heritage/booklet_excellence2.jpg",
            "images/CEPT/Living Heritage/booklet_excellence3.jpg",
            "images/CEPT/Living Heritage/booklet_excellence4.jpg",
            "images/CEPT/Living Heritage/booklet_excellence5.jpg",
            "images/CEPT/Living Heritage/exercises at site copy.jpg",
          ],
          video: "",
        },
        {
          id: "utopias-heterotopias",
          title: "From Utopias to Heterotopias",
          description: "A housing design project for informal settlements along Ahmedabad's creek edge — proposing clustered, inward-looking community units that organise shared space between them. The form is driven by social structure: each cluster of 7–8 units creates a semi-private commons, with staggered edges that dissolve the boundary between private and public. Semester 4, 2019.",
          images: [
            "images/CEPT/Utopias to Heterotopias/community-diagram.jpg",
            "images/CEPT/Utopias to Heterotopias/staggered-nodes.jpg",
            "images/CEPT/Utopias to Heterotopias/diagram-raghavsdfgc.jpg",
            "images/CEPT/Utopias to Heterotopias/diagram-raghavbngn.jpg",
            "images/CEPT/Utopias to Heterotopias/diagram-raghavsddfxb.jpg",
            "images/CEPT/Utopias to Heterotopias/diagram-raghavsv.jpg",
            "images/CEPT/Utopias to Heterotopias/section.jpg",
            "images/CEPT/Utopias to Heterotopias/masterplan-collage.jpg",
          ],
          video: "",
        },
        {
          id: "eco-machine",
          title: "Eco-machine",
          description: "A landscape urbanism project proposing an eco-machine on Mumbai's BKC waterfront — a tidal park that treats industrial waste, filters runoff, and creates habitat and livelihood for the fishing communities of Mahim. The design uses modular hexagonal bioremediation units arranged to follow tidal flows, creating a productive edge between the city and the sea. Semester 7, 2021.",
          images: [
            "images/CEPT/Eco-machine/render-01.jpg",
            "images/CEPT/Eco-machine/render-02.jpg",
            "images/CEPT/Eco-machine/axo.jpg",
            "images/CEPT/Eco-machine/22_Raghav Kohli.jpg",
            "images/CEPT/Eco-machine/01_Raghav Kohli.png",
            "images/CEPT/Eco-machine/02_Raghav Kohli.jpg",
            "images/CEPT/Eco-machine/03_Raghav Kohli.jpg",
            "images/CEPT/Eco-machine/04_Raghav Kohli.jpg",
            "images/CEPT/Eco-machine/05_Raghav Kohli.jpg",
            "images/CEPT/Eco-machine/06_Raghav Kohli.jpg",
            "images/CEPT/Eco-machine/07_Raghav Kohli.jpg",
            "images/CEPT/Eco-machine/08_Raghav Kohli.jpg",
            "images/CEPT/Eco-machine/09_Raghav Kohli.jpg",
            "images/CEPT/Eco-machine/10_Raghav Kohli.jpg",
            "images/CEPT/Eco-machine/11_Raghav Kohli.jpg",
            "images/CEPT/Eco-machine/12_Raghav Kohli.jpg",
            "images/CEPT/Eco-machine/13_Raghav Kohli.jpg",
            "images/CEPT/Eco-machine/14_Raghav Kohli.jpg",
            "images/CEPT/Eco-machine/15_Raghav Kohli.jpg",
          ],
          video: "",
        },
        {
          id: "generative-techniques",
          title: "Generative Techniques",
          description: "A computational design project using Grasshopper and evolutionary computation to generate and evaluate urban typologies for a mixed-use redevelopment site in Ahmedabad's Wadaj neighbourhood. Eight typologies were tested across eight performance objectives — sunlight, density, green space, connectivity — with Pareto-front optimisation to identify best-fit configurations. Semester 6, 2020.",
          images: [
            "images/CEPT/Generative Techniques/typology diag.jpg",
            "images/CEPT/Generative Techniques/density distribution.jpg",
            "images/CEPT/Generative Techniques/typology-T1.jpg",
            "images/CEPT/Generative Techniques/typology-T2.jpg",
            "images/CEPT/Generative Techniques/typology-T3.jpg",
            "images/CEPT/Generative Techniques/typology-T4.jpg",
            "images/CEPT/Generative Techniques/typology-T5.jpg",
            "images/CEPT/Generative Techniques/typology-T6.jpg",
            "images/CEPT/Generative Techniques/typology-T7.jpg",
            "images/CEPT/Generative Techniques/typology-T8.jpg",
          ],
          video: "",
        },
        {
          id: "water-urbanism",
          title: "Water Urbanism",
          description: "A landscape urbanism thesis exploring flood resilience and ecological restoration along Mumbai's Mithi River. Five months of fieldwork in fishing villages preceded the design — the project proposes a network of wetlands, eco-trails, urban agriculture zones, and riparian edge treatments to address drainage, ecology, and livelihoods simultaneously. Semester 9, 2021–22.",
          images: [
            "images/CEPT/Water Urbanism/masterplan.jpg",
            "images/CEPT/Water Urbanism/view 01.jpg",
            "images/CEPT/Water Urbanism/view 02.jpg",
            "images/CEPT/Water Urbanism/section.jpg",
            "images/CEPT/Water Urbanism/program diagram-01.jpg",
            "images/CEPT/Water Urbanism/wetland.jpg",
            "images/CEPT/Water Urbanism/ecotrail.jpg",
            "images/CEPT/Water Urbanism/food.jpg",
            "images/CEPT/Water Urbanism/street.jpg",
            "images/CEPT/Water Urbanism/aahar pyne.jpg",
            "images/CEPT/Water Urbanism/riperian edge and green cover.jpg",
            "images/CEPT/Water Urbanism/phase 02.jpg",
            "images/CEPT/Water Urbanism/phase 03.jpg",
          ],
          video: "",
        },
        {
          id: "open-source-urbanism",
          title: "Open Source Urbanism",
          description: "A Design Research Project on the Versova fishing village, Mumbai — mapping the open-source logics already embedded in the settlement: shared jetties, communal fish-drying grounds, bamboo construction, collective waste circuits. The project asks how design can make these systems legible and extensible rather than replace them. Semester 10, 2022.",
          images: [
            "images/CEPT/Open Source Urbanism/Artboard 1.jpg",
            "images/CEPT/Open Source Urbanism/Artboard 1 copy.jpg",
            "images/CEPT/Open Source Urbanism/Artboard 1 copy 2.jpg",
            "images/CEPT/Open Source Urbanism/Artboard 1 copy 3.jpg",
          ],
          video: "",
        },
        {
          id: "one-is-to-one",
          title: "One is to One",
          description: "A construction and structures studio exploring material honesty, load paths, and the relationship between drawing and making at full scale. Semester 3, 2018.",
          images: [],
          video: "",
        },
        {
          id: "overlapping-networks",
          title: "Overlapping Networks",
          description: "An urban analysis project mapping the layered infrastructures of a city — tracing how mobility, utilities, social, and ecological networks overlap, conflict, and co-produce urban space.",
          images: [],
          video: "",
        },
        {
          id: "majuli-island",
          title: "Exploring Majuli Island",
          description: "A winter school documentation project on Majuli — the world's largest river island, Assam — recording the culture, built environment, and human settlement patterns of the Mising and Deori communities in the face of annual floods and erosion.",
          images: [],
          video: "",
        },
        {
          id: "rebel-bodies",
          title: "Rebel Bodies Rebel Cities",
          description: "A design research project examining how marginalised bodies — queer, disabled, migrant — occupy, resist, and reimagine urban space. Explores the city as a site of both exclusion and insurgent inhabitation.",
          images: [],
          video: "",
        },
        {
          id: "designing-for-play",
          title: "Designing for Play",
          description: "A summer school exploring Aldo Van Eyck's Amsterdam playgrounds — studying how small, precise interventions in the leftover spaces of a post-war city created a network of democratic, child-centred public space.",
          images: [],
          video: "",
        },
        {
          id: "landscape-ecology",
          title: "Landscape and Ecology",
          description: "A studio examining the ecological systems underlying urban landscapes — working with soil, water, microclimate, and vegetation as active design material rather than backdrop.",
          images: [],
          video: "",
        },
        {
          id: "insurgent-public-spaces",
          title: "Insurgent Public Spaces",
          description: "A research and design studio on spaces of informal occupation — markets, shrines, protest sites, pavement economies — that exist outside sanctioned planning yet produce some of the most vital urban life.",
          images: [],
          video: "",
        },
        {
          id: "environmental-social-impact",
          title: "Environmental and Social Impact",
          description: "A policy and planning studio on Environmental and Social Impact Assessment — working through case studies of large urban infrastructure projects to understand the methodologies, politics, and limits of impact evaluation.",
          images: [],
          video: "",
        },
      ],
    },

    {
      id: "resilience-stack",
      title: "Resilience Stack",
      subtitle: "30 Days of Climate Intelligence",
      role: "Personal Project",
      year: "2025",
      category: "climate",
      featured: true,
      description: "30 standalone climate intelligence apps — maps, calculators, and dashboards built in 30 days. Each day layers a new dimension of the global climate crisis.",
      subprojects: [
        {
          id: "day01-grid-stress",
          title: "Day 01 — Global Grid Stress Map",
          description: "Country-level grid fragility score combining fossil dependency, energy access gap, and transmission loss. Year slider 2000–2023. Click any country for a deep-dive with projection to 50% clean energy.",
          link: "",
          images: [],
        },
        {
          id: "day02-solar-atlas",
          title: "Day 02 — Solar Potential Atlas",
          description: "Interactive global map of solar irradiance. Toggle satellite + rooftops mode, click any building to see panel yield, optimal tilt and azimuth from PVGIS, payback period, and CO₂ offset. Powered by NASA POWER.",
          link: "",
          images: [],
        },
      ],
    },

  ],

};
