const CONTENT = {

  heroImages: [
    // "images/hero/photo-1.jpg",
    // "images/hero/photo-2.jpg",
    // "images/hero/photo-3.jpg",
    // "images/hero/photo-4.jpg",
    // "images/hero/photo-5.jpg",
  ],

  name: "Raghav Kohli",
  title: "Urban Designer · Climate Strategist",
  location: "Bengaluru, India",
  email: "raghav.kohli.work@gmail.com",
  linkedin: "linkedin.com/in/raghavkohli31",

  hero: {
    headline: ["Cities", "Community", "Climate"],
    statement: "I went to the ground first — five months in Mumbai's fishing villages before I drew a single line.",
  },

  projects: [

    {
      id: "iclei",
      title: "ICLEI",
      subtitle: "Local Governments for Sustainability",
      role: "Project Officer, Climate & Energy",
      year: "2024",
      category: "climate",
      featured: true,
      description: "Led climate strategy and policy work across South and Southeast Asia.",
      subprojects: [
        {
          id: "malaysia",
          title: "Malaysia Green City Action Plan",
          description: "City-level climate strategy spanning 5 municipalities, coordinated with national government counterparts.",
          images: [
            "images/ICLEI/placeholder.png",
          ],
          video: "",
        },
        {
          id: "capacities",
          title: "CapaCities",
          description: "Capacity building programme for local government officials across South Asian cities.",
          images: [],
          video: "",
        },
        {
          id: "loss-damage",
          title: "Loss & Damage",
          description: "Multilateral policy briefs on Loss & Damage for international climate negotiations.",
          images: [],
          video: "",
        },
        {
          id: "urban95",
          title: "Udaipur Urban95",
          description: "Child-Friendly Cities assessment integrating child-sensitive spatial design into the municipal planning framework.",
          images: [],
          video: "",
        },
        {
          id: "clean-energy",
          title: "US–South Asia Mayoral Platform",
          description: "Clean Energy platform facilitating dialogue between city leaders across two continents.",
          images: [],
          video: "",
        },
      ],
    },

    {
      id: "niua",
      title: "NIUA",
      subtitle: "National Institute of Urban Affairs, MoHUA India",
      role: "Climate Fellow, Climate Center for Cities",
      year: "2023",
      category: "climate",
      featured: true,
      description: "Climate policy research and toolkit development for Indian cities.",
      subprojects: [
        {
          id: "state-of-cities",
          title: "State of Cities",
          description: "Towards Low Carbon and Resilient Pathways — national policy report covering 15 Indian cities, published by MoHUA. Presented at the G20 Urban20 Summit, Ahmedabad, July 2023.",
          viewer: "reader",
          stats: [
            { n: "15",   l: "Cities Profiled" },
            { n: "24M",  l: "People" },
            { n: "38M",  l: "tCO₂e GHG" },
            { n: "319",  l: "Actions Mapped" },
          ],
          sections: [
            { label: "Cover",         start: 1,  end: 3  },
            { label: "Foreword",      start: 4,  end: 7  },
            { label: "Global View",   start: 8,  end: 12 },
            { label: "National View", start: 13, end: 15 },
            { label: "City View",     start: 16, end: 32 },
            { label: "Way Forward",   start: 33, end: 38 },
          ],
          cities: [
            { name: "Ahmedabad",        state: "Gujarat",          page: 18 },
            { name: "Coimbatore",       state: "Tamil Nadu",        page: 19 },
            { name: "Gwalior",          state: "Madhya Pradesh",    page: 20 },
            { name: "Kochi",            state: "Kerala",            page: 21 },
            { name: "Nagpur",           state: "Maharashtra",       page: 22 },
            { name: "Panaji",           state: "Goa",               page: 23 },
            { name: "Pimpri-Chinchwad", state: "Maharashtra",       page: 24 },
            { name: "Rajkot",           state: "Gujarat",           page: 25 },
            { name: "Shimla",           state: "Himachal Pradesh",  page: 26 },
            { name: "Siliguri",         state: "West Bengal",       page: 27 },
            { name: "Thane",            state: "Maharashtra",       page: 28 },
            { name: "Tiruchirappalli",  state: "Tamil Nadu",        page: 29 },
            { name: "Tirunelveli",      state: "Tamil Nadu",        page: 30 },
            { name: "Udaipur",          state: "Rajasthan",         page: 31 },
            { name: "Vadodara",         state: "Gujarat",           page: 32 },
          ],
          images: [
            "images/NIUA/State-of-cities/Final Book version_page-0001.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0002.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0003.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0004.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0005.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0006.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0007.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0008.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0009.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0010.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0011.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0012.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0013.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0014.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0015.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0016.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0017.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0018.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0019.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0020.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0021.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0022.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0023.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0024.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0025.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0026.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0027.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0028.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0029.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0030.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0031.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0032.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0033.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0034.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0035.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0036.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0037.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0038.jpg",
          ],
          video: "",
        },
        {
          id: "compendium",
          title: "Compendium of Good Climate Practices",
          description: "Researched and documented climate interventions across 15+ municipalities for national policy adoption.",
          images: [],
          video: "",
        },
        {
          id: "nbs-toolkit",
          title: "Nature-based Solutions Toolkit",
          description: "Practical NbS implementation guidance developed for urban local bodies across India.",
          images: [],
          video: "",
        },
      ],
    },

    {
      id: "perspectives",
      title: "Perspectives",
      subtitle: "Community Platform",
      role: "Co-founder",
      year: "2025 – Present",
      category: "community",
      featured: true,
      description: "8 to 1,000+ members through word of mouth. A community built around structured human conversation.",
      stats: [
        { number: "200+", label: "Conversations hosted" },
        { number: "1K+",  label: "Members, zero paid acquisition" },
        { number: "3",    label: "Formats — Spheres, Circles, Home" },
      ],
      conversations: [
        {
          id: "conv-001",
          title: "What does it mean to belong to a city?",
          description: "A conversation about urban identity, belonging, and what makes a city feel like home.",
          initiator: "Raghav Kohli",
          date: "2025-03",
          format: "Sphere",
          photo: "",
          recording: "",
        },
        {
          id: "conv-002",
          title: "On grief and growth",
          description: "An intimate Sphere exploring how loss shapes identity and the relationships we build after.",
          initiator: "Shreshtha",
          date: "2025-04",
          format: "Sphere",
          photo: "",
          recording: "",
        },
        {
          id: "conv-003",
          title: "Climate anxiety and what we do with it",
          description: "How do people working in climate actually feel about the future? An honest conversation.",
          initiator: "Raghav Kohli",
          date: "2025-05",
          format: "Circle",
          photo: "",
          recording: "",
        },
        {
          id: "conv-004",
          title: "Career pivots and the identity that follows",
          description: "When you change what you do, who do you become? Hosted across three living rooms.",
          initiator: "Avani",
          date: "2025-06",
          format: "Home",
          photo: "",
          recording: "",
        },
      ],
      subprojects: [],
    },

    {
      id: "cept",
      title: "CEPT University",
      subtitle: "Centre for Environmental Planning & Technology",
      role: "Bachelor of Urban Design",
      year: "2017 – 2022",
      category: "design",
      featured: true,
      description: "Five years of urban design education, research, and fieldwork.",
      subprojects: [
        // {
        //   id: "living-heritage",
        //   title: "Living Heritage",
        //   description: "Co-designing to Revive Historical Identity. Winner, CEPT Student Excellence Award.",
        //   images: [],
        //   video: "",
        // },
      ],
    },

  ],

};
