const CONTENT = {

  heroImages: [
    // "images/hero/photo-1.jpg",
    // "images/hero/photo-2.jpg",
    // "images/hero/photo-3.jpg",
    // "images/hero/photo-4.jpg",
    // "images/hero/photo-5.jpg",
  ],

  name: "Raghav Kohli",
  title: "Urban Designer · Climate Strategist",
  location: "Bengaluru, India",
  email: "raghav.kohli.work@gmail.com",
  linkedin: "linkedin.com/in/raghavkohli31",

  hero: {
    headline: ["Cities", "Community", "Climate"],
    statement: "I went to the ground first — five months in Mumbai's fishing villages before I drew a single line.",
  },

  projects: [

    {
      id: "iclei",
      title: "ICLEI",
      subtitle: "Local Governments for Sustainability",
      role: "Project Officer, Climate & Energy",
      year: "2024",
      category: "climate",
      featured: true,
      description: "Led climate strategy and policy work across South and Southeast Asia.",
      subprojects: [
        {
          id: "malaysia",
          title: "Malaysia Green City Action Plan",
          description: "City-level climate strategy spanning 5 municipalities, coordinated with national government counterparts.",
          images: [
            "images/ICLEI/placeholder.png",
          ],
          video: "",
        },
        {
          id: "capacities",
          title: "CapaCities",
          description: "Capacity building programme for local government officials across South Asian cities.",
          images: [],
          video: "",
        },
        {
          id: "loss-damage",
          title: "Loss & Damage",
          description: "Multilateral policy briefs on Loss & Damage for international climate negotiations.",
          images: [],
          video: "",
        },
        {
          id: "urban95",
          title: "Udaipur Urban95",
          description: "Child-Friendly Cities assessment integrating child-sensitive spatial design into the municipal planning framework.",
          images: [],
          video: "",
        },
        {
          id: "clean-energy",
          title: "US–South Asia Mayoral Platform",
          description: "Clean Energy platform facilitating dialogue between city leaders across two continents.",
          images: [],
          video: "",
        },
        {
          id: "vadodara-crcap",
          title: "Vadodara Climate Resilient City Action Plan",
          description: "Towards a Net Zero Future — a comprehensive climate action plan for Vadodara Municipal Corporation, developed with ICLEI South Asia. Covers climate risk assessment, sectoral emissions, and adaptation and mitigation action plans across transport, energy, water, waste, and urban greening. August 2024.",
          viewer: "reader",
          images: [
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-0.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-1.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-2.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-3.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-4.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-5.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-6.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-7.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-8.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-9.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-10.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-11.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-12.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-13.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-14.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-15.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-16.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-17.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-18.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-19.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-20.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-21.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-22.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-23.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-24.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-25.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-26.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-27.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-28.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-29.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-30.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-31.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-32.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-33.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-34.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-35.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-36.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-37.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-38.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-39.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-40.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-41.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-42.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-43.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-44.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-45.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-46.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-47.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-48.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-49.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-50.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-51.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-52.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-53.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-54.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-55.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-56.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-57.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-58.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-59.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-60.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-61.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-62.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-63.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-64.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-65.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-66.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-67.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-68.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-69.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-70.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-71.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-72.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-73.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-74.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-75.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-76.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-77.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-78.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-79.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-80.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-81.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-82.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-83.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-84.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-85.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-86.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-87.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-88.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-89.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-90.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-91.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-92.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-93.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-94.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-95.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-96.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-97.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-98.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-99.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-100.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-101.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-102.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-103.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-104.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-105.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-106.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-107.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-108.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-109.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-110.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-111.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-112.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-113.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-114.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-115.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-116.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-117.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-118.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-119.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-120.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-121.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-122.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-123.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-124.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-125.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-126.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-127.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-128.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-129.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-130.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-131.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-132.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-133.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-134.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-135.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-136.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-137.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-138.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-139.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-140.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-141.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-142.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-143.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-144.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-145.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-146.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-147.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-148.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-149.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-150.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-151.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-152.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-153.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-154.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-155.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-156.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-157.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-158.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-159.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-160.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-161.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-162.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-163.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-164.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-165.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-166.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-167.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-168.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-169.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-170.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-171.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-172.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-173.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-174.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-175.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-176.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-177.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-178.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-179.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-180.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-181.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-182.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-183.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-184.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-185.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-186.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-187.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-188.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-189.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-190.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-191.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-192.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-193.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-194.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-195.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-196.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-197.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-198.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-199.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-200.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-201.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-202.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-203.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-204.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-205.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-206.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-207.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-208.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-209.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-210.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-211.jpg",
            "images/ICLEI/Ahmedabad Climate Resilient City Action Plan/240911_Vadodara CRCAP_Combined Book_Final Version_4_compressed-compressed-images-212.jpg",
          ],
          video: "",
        },
      ],
    },

    {
      id: "niua",
      title: "NIUA",
      subtitle: "National Institute of Urban Affairs, MoHUA India",
      role: "Climate Fellow, Climate Center for Cities",
      year: "2023",
      category: "climate",
      featured: true,
      description: "Climate policy research and toolkit development for Indian cities.",
      subprojects: [
        {
          id: "state-of-cities",
          title: "State of Cities",
          description: "Towards Low Carbon and Resilient Pathways — national policy report covering 15 Indian cities, published by MoHUA. Presented at the G20 Urban20 Summit, Ahmedabad, July 2023.",
          viewer: "reader",
          stats: [
            { n: "15",   l: "Cities Profiled" },
            { n: "24M",  l: "People" },
            { n: "38M",  l: "tCO₂e GHG" },
            { n: "319",  l: "Actions Mapped" },
          ],
          sections: [
            { label: "Cover",         start: 1,  end: 3  },
            { label: "Foreword",      start: 4,  end: 7  },
            { label: "Global View",   start: 8,  end: 12 },
            { label: "National View", start: 13, end: 15 },
            { label: "City View",     start: 16, end: 32 },
            { label: "Way Forward",   start: 33, end: 38 },
          ],
          cities: [
            { name: "Ahmedabad",        state: "Gujarat",          page: 18 },
            { name: "Coimbatore",       state: "Tamil Nadu",        page: 19 },
            { name: "Gwalior",          state: "Madhya Pradesh",    page: 20 },
            { name: "Kochi",            state: "Kerala",            page: 21 },
            { name: "Nagpur",           state: "Maharashtra",       page: 22 },
            { name: "Panaji",           state: "Goa",               page: 23 },
            { name: "Pimpri-Chinchwad", state: "Maharashtra",       page: 24 },
            { name: "Rajkot",           state: "Gujarat",           page: 25 },
            { name: "Shimla",           state: "Himachal Pradesh",  page: 26 },
            { name: "Siliguri",         state: "West Bengal",       page: 27 },
            { name: "Thane",            state: "Maharashtra",       page: 28 },
            { name: "Tiruchirappalli",  state: "Tamil Nadu",        page: 29 },
            { name: "Tirunelveli",      state: "Tamil Nadu",        page: 30 },
            { name: "Udaipur",          state: "Rajasthan",         page: 31 },
            { name: "Vadodara",         state: "Gujarat",           page: 32 },
          ],
          images: [
            "images/NIUA/State-of-cities/Final Book version_page-0001.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0002.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0003.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0004.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0005.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0006.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0007.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0008.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0009.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0010.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0011.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0012.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0013.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0014.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0015.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0016.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0017.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0018.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0019.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0020.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0021.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0022.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0023.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0024.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0025.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0026.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0027.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0028.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0029.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0030.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0031.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0032.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0033.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0034.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0035.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0036.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0037.jpg",
            "images/NIUA/State-of-cities/Final Book version_page-0038.jpg",
          ],
          video: "",
        },
        {
          id: "compendium",
          title: "Compendium of Good Climate Practices",
          description: "Researched and documented climate interventions across 15+ municipalities for national policy adoption.",
          images: [],
          video: "",
        },
        {
          id: "nbs-toolkit",
          title: "Nature-based Solutions Toolkit",
          description: "Practical NbS implementation guidance developed for urban local bodies across India.",
          images: [],
          video: "",
        },
      ],
    },

    {
      id: "perspectives",
      title: "Perspectives",
      subtitle: "Community Platform",
      role: "Co-founder",
      year: "2025 – Present",
      category: "community",
      featured: true,
      description: "8 to 1,000+ members through word of mouth. A community built around structured human conversation.",
      stats: [
        { number: "200+", label: "Conversations hosted" },
        { number: "1K+",  label: "Members, zero paid acquisition" },
        { number: "3",    label: "Formats — Spheres, Circles, Home" },
      ],
      conversations: [
        {
          id: "conv-001",
          title: "What does it mean to belong to a city?",
          description: "A conversation about urban identity, belonging, and what makes a city feel like home.",
          initiator: "Raghav Kohli",
          date: "2025-03",
          format: "Sphere",
          photo: "",
          recording: "",
        },
        {
          id: "conv-002",
          title: "On grief and growth",
          description: "An intimate Sphere exploring how loss shapes identity and the relationships we build after.",
          initiator: "Shreshtha",
          date: "2025-04",
          format: "Sphere",
          photo: "",
          recording: "",
        },
        {
          id: "conv-003",
          title: "Climate anxiety and what we do with it",
          description: "How do people working in climate actually feel about the future? An honest conversation.",
          initiator: "Raghav Kohli",
          date: "2025-05",
          format: "Circle",
          photo: "",
          recording: "",
        },
        {
          id: "conv-004",
          title: "Career pivots and the identity that follows",
          description: "When you change what you do, who do you become? Hosted across three living rooms.",
          initiator: "Avani",
          date: "2025-06",
          format: "Home",
          photo: "",
          recording: "",
        },
      ],
      subprojects: [],
    },

    {
      id: "cept",
      title: "CEPT University",
      subtitle: "Centre for Environmental Planning & Technology",
      role: "Bachelor of Urban Design",
      year: "2017 – 2022",
      category: "design",
      featured: true,
      description: "Five years of urban design education, research, and fieldwork.",
      subprojects: [
        // {
        //   id: "living-heritage",
        //   title: "Living Heritage",
        //   description: "Co-designing to Revive Historical Identity. Winner, CEPT Student Excellence Award.",
        //   images: [],
        //   video: "",
        // },
      ],
    },

  ],

};
