// The fuller archive shown in the (index) section — everything real that is not (yet) a card.
// One row per item, same register as the cards. `media` + `blurb` drive the sticky hover-preview
// pane on the right; point `href` at a page or PDF when one exists. Numbering continues after the
// homepage cards (17 as of 2026-09-18). Sources: D:\Work — see memory/pipeline-2026-09-17.
module.exports = [
  { n: "18", name: "flood resilience strategy", cat: "niua · aligarh", year: "2023",
    media: "fig.18 — ward-level blue-green map",
    blurb: "A flood resilience strategy template, tested on Aligarh — ward-level blue-green mapping for a city that grew as ribbon sprawl along its highways." },
  { n: "19", name: "climate dialogues", cat: "niua · india climate dialogue", year: "2023",
    media: "fig.19 — session frame",
    blurb: "Sessions on operationalising nature-based solutions in river cities and on urban water management — the conversations behind the reports, edited for a public audience." },
  { n: "20", name: "urban95 udaipur", cat: "iclei south asia · child-friendly cities", year: "2024",
    media: "fig.20 — a street at 95 cm",
    blurb: "An assessment of Udaipur from 95 centimetres — ethnographic fieldwork with children and caregivers, translated into spatial recommendations for the city." },
  { n: "21", name: "common ground", cat: "studio commons · prospectus", year: "2025",
    media: "fig.21 — prospectus spread",
    blurb: "Studio Commons' 2025 prospectus — participatory design and urban research offered as a service a city, a trust or an agency can procure." },
  { n: "22", name: "rural city", cat: "research · buranest, ethiopia", year: "2019—2021",
    media: "fig.22 — buranest, diagram",
    blurb: "A manual for new towns, studied from one being built — what a settlement needs before it needs a plan." },
  { n: "23", name: "informal public spaces", cat: "workshop · guide", year: "2021",
    media: "fig.23 — the guide",
    blurb: "A guide to the public spaces no plan drew — documented, categorised, and argued for." },
  { n: "24", name: "sea level rise", cat: "competition · singapore", year: "2023",
    media: "fig.24 — the high-water line",
    blurb: "A coastal city asked to draw its own high-water line — competition entry." },
  { n: "25", name: "design for play", cat: "summer school · amsterdam", year: "2018",
    media: "fig.25 — streets as playgrounds",
    blurb: "Aldo van Eyck's playgrounds, walked and drawn — everyday streets read as playgrounds, the seed of the play structures in living heritage." },
  { n: "26", name: "low-carbon materials", cat: "study trip · research", year: "2024—2025",
    media: "fig.26 — brick kiln, drawn",
    blurb: "Brick kilns and plywood factories visited, measured and drawn — where a building's carbon begins, before the site." },
  { n: "27", name: "full cv", cat: "complete record · pdf", year: "2026", href: "/assets/Raghav_Kohli_CV.pdf",
    media: "fig.27 — curriculum vitae",
    blurb: "The complete record — roles, publications, projects and teaching in one document, for the reader who wants everything in order." },
];
